// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNtV2cQf50KLefuIkD_Uy3kjE8MQi0xM',
    appId: '1:52444324463:web:60ec508045a84817b9a39a',
    messagingSenderId: '52444324463',
    projectId: 'reachex-e4ca8',
    authDomain: 'reachex-e4ca8.firebaseapp.com',
    storageBucket: 'reachex-e4ca8.firebasestorage.app',
    measurementId: 'G-H78K0XRLGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIEAMfKFmsekpA3SiryzQRQ31TMQ3x3jA',
    appId: '1:52444324463:android:1d16a183680ebc03b9a39a',
    messagingSenderId: '52444324463',
    projectId: 'reachex-e4ca8',
    storageBucket: 'reachex-e4ca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Hczwi9OkB_-TxJGlo6l_KaSAN-CDjYw',
    appId: '1:52444324463:ios:f1ed2b76d4262dc9b9a39a',
    messagingSenderId: '52444324463',
    projectId: 'reachex-e4ca8',
    storageBucket: 'reachex-e4ca8.firebasestorage.app',
    iosBundleId: 'com.reachex.app',
  );

}