import 'package:get_it/get_it.dart';
import 'package:reachx_embed/core/subscription/subscriptionController.dart';
import 'package:reachx_embed/data/booked/bookedRepoImpl.dart';
import 'package:reachx_embed/data/booking/bookingRepoImpl.dart';
import 'package:reachx_embed/data/checkLog/checkLogRepoImpl.dart';
import 'package:reachx_embed/data/expertDetail/expertDetailRepoImpl.dart';
import 'package:reachx_embed/data/expertRegistration/expertRegistrationRepoImpl.dart';
import 'package:reachx_embed/data/homescreen/homeScreenRepoImpl.dart';
import 'package:reachx_embed/data/meetingSetup/meetingSetupRepoImpl.dart';
import 'package:reachx_embed/data/passionGenerator/passionGeneratorRepoImpl.dart';
import 'package:reachx_embed/data/profile/profileExpertRepoImpl.dart';
import 'package:reachx_embed/data/sessionDetail/sessionDetailRepoImpl.dart';
import 'package:reachx_embed/data/signUp/signUpRepoImpl.dart';
import 'package:reachx_embed/data/splash/splashRepoImpl.dart';
import 'package:reachx_embed/data/topicList/topicListRepoImpl.dart';
import 'package:reachx_embed/data/topicUpload/topicUploadRepoImpl.dart';
import 'package:reachx_embed/data/wallet/walletRepoImpl.dart';
import 'package:reachx_embed/domain/booked/bookedRepo.dart';
import 'package:reachx_embed/domain/booking/bookingRepo.dart';
import 'package:reachx_embed/domain/checkLog/checkLogRepo.dart';
import 'package:reachx_embed/domain/expertDetail/expertDetailRepo.dart';
import 'package:reachx_embed/domain/expertRegistration/expertRegistrationRepo.dart';
import 'package:reachx_embed/domain/homeScreen/homeScreenRepo.dart';
import 'package:reachx_embed/domain/meetingSetup/meetingSetupRepo.dart';
import 'package:reachx_embed/domain/passionGenerator/passionGeneratorRepo.dart';
import 'package:reachx_embed/domain/profile/profileExpertRepo.dart';
import 'package:reachx_embed/domain/sessionDetail/sessionDetailRepo.dart';
import 'package:reachx_embed/domain/signUp/signUpRepo.dart';
import 'package:reachx_embed/domain/splash/splashRepo.dart';
import 'package:reachx_embed/domain/topicList/topicListRepo.dart';
import 'package:reachx_embed/domain/topicUpload/topicUploadRepo.dart';
import 'package:reachx_embed/domain/wallet/walletRepo.dart';
import 'package:reachx_embed/presentation/mentoring/booked/bookedViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/booking/bookingViewModel.dart';
import 'package:reachx_embed/presentation/commonWidgets/topicDisplayContainer.dart';
import 'package:reachx_embed/presentation/mentoring/expertDetail/expertDetailViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/expert_registration/expertRegistrationViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/homeScreen/homeScreenViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/meetingSetup/meetingSetupViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/profile/profileViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/sessionDetail/sessionDetailViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/signUp/signUpViewModel.dart';
import 'package:reachx_embed/presentation/mentoring/wallet/walletViewModel.dart';

GetIt getIt = GetIt.instance;

initInjection() {
  getIt.registerSingleton<SignUpViewModel>(SignUpViewModel());
  getIt.registerSingleton<SignUpRepo>(SignUpRepoImpl());
  getIt.registerSingleton<ExpertDetailRepo>(ExpertDetailRepoImpl());
  getIt.registerSingleton<CheckLogRepo>(CheckLogRepoImpl());
  getIt.registerSingleton<TopicListRepo>(TopicListRepoImpl());
  getIt.registerSingleton<ExpertRegistrationRepo>(ExpertRegistrationRepoImpl());
  getIt.registerSingleton<HomeScreenRepo>(HomeScreenRepoImpl());
  getIt.registerSingleton<ProfileExpertRepo>(ProfileExpertRepoImpl());
  getIt.registerSingleton<BookingRepo>(BookingRepoImpl());
  getIt.registerSingleton<BookedRepo>(BookedRepoImpl());
  getIt.registerSingleton<BookedViewModel>(BookedViewModel());
  getIt.registerSingleton<ExpertRegistrationViewModel>(ExpertRegistrationViewModel());
  getIt.registerSingleton<SessionDetailRepo>(SessionDetailRepoImpl());
  getIt.registerSingleton<BookingViewModel>(BookingViewModel());
  getIt.registerSingleton<ProfileViewModel>(ProfileViewModel());
  getIt.registerSingleton<SessionDetailViewModel>(SessionDetailViewModel());
  getIt.registerSingleton<MeetingSetupRepo>(MeetingSetupRepoImpl());
  getIt.registerSingleton<ExpertDetailViewModel>(ExpertDetailViewModel());
  getIt.registerSingleton<MeetingSetupViewModel>(MeetingSetupViewModel());
  getIt.registerSingleton<HomeScreenViewModel>(HomeScreenViewModel());
  getIt.registerSingleton<AudioCoordinator>(AudioCoordinator());
  getIt.registerSingleton<WalletRepo>(WalletRepoImpl());
  getIt.registerSingleton<TopicUploadRepo>(TopicUploadRepoImpl());
  getIt.registerSingleton<WalletViewModel>(WalletViewModel());
  getIt.registerSingleton<PassionGeneratorRepo>(PassionGeneratorRepoImpl());
  getIt.registerSingleton<SubscriptionController>(SubscriptionController());
  getIt.registerSingleton<SplashRepo>(SplashRepoImpl());
}